/*
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.inf.mdd2.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class TurtlesScopeProvider extends AbstractTurtlesScopeProvider {

}
